include: package:flutter_lints/flutter.yaml

linter:
  # https://dart-lang.github.io/linter/lints/index.html.
  #
  rules:
    always_declare_return_types: true
    avoid_print: true
    prefer_single_quotes: true
    cancel_subscriptions: true
    await_only_futures: true
    valid_regexps: true
    constant_identifier_names: false
    file_names: true
    close_sinks: true
    prefer_relative_imports: true
    avoid_relative_lib_imports: true


    avoid_web_libraries_in_flutter: true
    hash_and_equals: true

    unrelated_type_equality_checks: true

    always_require_non_null_named_parameters: true

    annotate_overrides: true

    avoid_function_literals_in_foreach_calls: true
    avoid_init_to_null: true
    avoid_unnecessary_containers: true
    avoid_slow_async_io: true

    avoid_null_checks_in_equality_operators: true
    avoid_multiple_declarations_per_line: true
    avoid_return_types_on_setters: true
    avoid_returning_null: true

    prefer_void_to_null: true
    empty_constructor_bodies: true
    avoid_single_cascade_in_expression_statements: true
    avoid_returning_null_for_void: true

    prefer_equal_for_default_values: true
    use_rethrow_when_possible: true
    prefer_generic_function_type_aliases: true




analyzer:
  exclude:
    - lib/client.dart
    - lib/server/*.g.dart
# Additional information about this file can be found at
# https://dart.dev/guides/language/analysis-options
