name: mail_tm
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.17.6 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  flutter_screenutil: ^5.5.3+2
  get: 4.6.5
  get_storage: ^2.0.3
  logger: ^1.1.0
  connectivity_plus: ^2.2.1
  google_fonts: ^3.0.1
  pull_to_refresh: #^2.0.0
    git:
      url: https://github.com/ymback/flutter_pulltorefresh.git

  flutter: 
    sdk: flutter
  styled_widget: ^0.4.0+3

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

